build:
  zip:
    composer:
      enabled: false
    assets:
      enabled: false
    pack:
      excludes:
        paths:
          - var
          - .gitignore

store:
  availabilities:
    - German
    - International
  default_locale: en_GB
  localizations:
    - de_DE
    - en_GB
  categories:
    - Administration
  type: extension
  icon: src/Resources/config/plugin.png
  automatic_bugfix_version_compatibility: true
  description:
    de: file:src/Resources/store/de.md
    en: file:src/Resources/store/en.md
  installation_manual:
    de: file:src/Resources/store/de_manual.md
    en: file:src/Resources/store/en_manual.md
  tags:
    de:
      - Tools
      - Testsystem
      - Passwortschutz
    en:
      - tools
      - password protection
      - test system
  videos:
    de: [ ]
    en: [ ]
  highlights:
    de:
      - Storefront mit Passwort schützen
      - IP-Adressen freigeben
      - keine separate Benutzerpflege notwendig
    en:
      - Protect storefront with password
      - Allow IP addresses
      - No separate user management necessary
  features:
    de:
      - Passwortschutz für Storefront
      - Freigabe von IP-Adressen
      - Freigabe von bestimmten Benutzerrollen
      - keine separate Benutzerpflege notwendig
    en:
      - Password protection for storefront
      - Allow IP addresses
      - Allow specific user roles
      - no separate user management necessary
  faq:
    de: [ ]
    en: [ ]
  images:
    - file: src/Resources/store/screenshot_settings.png
      activate:
        de: true
        en: true
      preview:
        de: true
        en: true
      priority: 0

changelog:
  enabled: true
