name: Publish extension
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_and_publish:
    uses: shopware/github-actions/.github/workflows/store-release.yml@16a16ee8ea4062f3b339b42e31fbddb7fa6fbbce
    with:
      extensionName: JeboehmAccessProtection
    secrets:
      accountUser: ${{ secrets.ACCOUNT_USER }}
      accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}
