---

name: Publish extension
on:
  workflow_dispatch:

jobs:
  build_and_publish:
    uses: shopware/github-actions/.github/workflows/store-release.yml@641b51465fa77989b8bbe345665681212be3e385
    with:
      extensionName: JeboehmAccessProtection
    secrets:
      accountUser: ${{ secrets.ACCOUNT_USER }}
      accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}
