---

name: Publish extension
on:
  workflow_dispatch:

jobs:
  build_and_publish:
    uses: shopware/github-actions/.github/workflows/store-release.yml@5a7a60b85f5beca11c13d36a964fd3b96a74bceb
    with:
      extensionName: JeboehmAccessProtection
    secrets:
      accountUser: ${{ secrets.ACCOUNT_USER }}
      accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}
