---

name: Build extension
on:
  workflow_dispatch:

jobs:
  build:
    uses: shopware/github-actions/.github/workflows/store-release.yml@main
    with:
      extensionName: JeboehmAccessProtection
    secrets:
      accountUser: ${{ secrets.ACCOUNT_USER }}
      accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}
