name: Test
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  phpstan:
    uses: shopware/github-actions/.github/workflows/phpstan.yml@5a7a60b85f5beca11c13d36a964fd3b96a74bceb
    with:
      extensionName: JeboehmAccessProtection
  zip:
    uses: shopware/github-actions/.github/workflows/build-zip.yml@5a7a60b85f5beca11c13d36a964fd3b96a74bceb
    with:
      extensionName: JeboehmAccessProtection
      #  phpunit:
      #    uses: shopware/github-actions/.github/workflows/phpunit.yml@main
      #    with:
      #      extensionName: JeboehmAccessProtection
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 'lts/*'
      - name: Run Check
        uses: shopware/github-actions/extension-verifier@5a7a60b85f5beca11c13d36a964fd3b96a74bceb
        with:
          action: check
