name: Test
on:
  push:
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: "5 15 * * *"

jobs:
  test:
    env:
      PLUGIN_NAME: JeboehmAccessProtection
    strategy:
      fail-fast: false
      matrix:
        version: [ "v6.5.8.7" ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          shopware-version: ${{ matrix.version }}
          php-version: 8.2
          php-extensions: pcov
          install: true

      - name: Info
        run: |
          php bin/console -V
          mysql -V
          php -v

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}

      - name: PHPStan
        working-directory: ${{ github.workspace }}
        run: |
          composer require jeboehm/platform-access-protection
          ${{ github.workspace }}/vendor/bin/phpstan analyse -c ${{ github.workspace }}/custom/plugins/${{ env.PLUGIN_NAME }}/phpstan.neon
