name: Test
on:
  push:
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: "5 15 * * *"

jobs:
  phpstan:
    uses: shopware/github-actions/.github/workflows/phpstan.yml@main
    with:
      extensionName: JeboehmAccessProtection
      shopwareVersion: v6.6.0.1

  zip:
    uses: shopware/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: JeboehmAccessProtection
