name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    uses: shopware/github-actions/.github/workflows/phpstan.yml@main
    with:
      extensionName: JeboehmAccessProtection

  zip:
    uses: shopware/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: JeboehmAccessProtection

#  phpunit:
#    uses: shopware/github-actions/.github/workflows/phpunit.yml@main
#    with:
#      extensionName: JeboehmAccessProtection

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Run Check
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
